### ISSUE TITLE
Invalid Url!

### ISSUE THREAD

**Issue by Gabri04** [RobinSchfr/Knowunity-Grabber#1]
Hi, it doesn't work, I even tried your link and always shows Invalid Url.

**Comment by RobinSchfr** [comment]
Hey,
thank you for the issue.
So I just checked the script again and it should still work properly. Did you make sure that there is no whitespace before the link? The link has to start with `https://knowunity.de/knows/`

**Comment by Gabri04** [comment]
The problem is now solved, I also changed the link to start with in my country. I really thank you so much for this amazing feature, I've been really struggling to find a way for days. Is there a way I can thank you? Perhaps, do you have Paypal?

**Comment by RobinSchfr** [comment]
I'm glad that your problem is now solved.
I want to thank you that you mentioned the problem with the different country. I've just updated the script to allow multi-language support ([9f620c9](https://github.com/RobinSchfr/Knowunity-Grabber/commit/9f620c99d174961099da09ac1a53ee9f8afaa03d)). Now every top-level domain from Knowunity will be accepted.

I'm just happy when my projects are actually useful for people.
But don't feel obligated to donate something, only if you really want to.
This is my paypal link: https://www.paypal.com/paypalme/RbnSchfr

**I appreciate your interest in my work.**
